### ISSUE TITLE
URDF Joints and Transmission

### ISSUE THREAD

**Issue by robodhruv** [iitbmartian/GUI#2]
Running `msi_2k16_17_gazebo/launch/msi.launch` throws exceptions about failure in loading joints and deprecated transmission type. Attached below is a screen of the same.

![image](https://cloud.githubusercontent.com/assets/14254187/23397914/67af6bea-fdc0-11e6-807c-a7778c826fd1.png)

I am guessing there is an issue with the URDF file. This works fine with a similar process in [the simulation repo](https://github.com/iitbmartian/rover_simulation)

**Comment by Agrim9** [comment]
Yes, the current URDF model hasn't been adapted for Gazebo (The inertia tags etc are not proper). I'm guessing it shouldn't take much time for you to correct them (as you'd done with the previous model). Please reply ASAP on this, otherwise I'll assign pranay to correct them. Is it getting visualised properly on RViz?

**Comment by robodhruv** [comment]
The URDF works just fine when using it in the [Simulation Repo](https://github.com/iitbmartian/rover_simulation). I guess this repo has not been updated. I'll make a PR soon.

**Comment by Agrim9** [comment]
Yes, I think I should remove the gazebo part from this repo, given that simulation has got it's own repo now. This has caused confusion, I guess.

**Comment by robodhruv** [comment]
Resolved. Let the gazebo package remain for the sake of completeness.

173256f9c2aa606c9562bc06e35d6537c6c7010d
